### ISSUE TITLE
Cant get it to work.

### ISSUE THREAD

**Issue by crazywolf132** [lentech/botster#1]
Hey, I managed to get this project working once on a mac, but that was a complete stroke of luck. I am trying to get this project running on my web server on my Raspberry Pi 2, but it just wont work. It is trying to find the "http://my-ip/botster/ajax/conversations/create" I have a feeling it is to do with the the .htaccess but I am not sure. I am having a similar problem with "http://my-ip/botster/ajax/say". Please help me, as I have an idea and i would like to make something for my raspberry pi with it. I am willing to give you full SSH and ftp access to it over Skype or email.

Email: crazywolf132@gmail.com
Skype: b2moon.au

**Comment by lenton** [comment]
Weirdly enough, I got my first raspberry pi for Christmas and am planning to do a project using Botster too.

Have you [enabled htaccess files](https://help.ubuntu.com/community/EnablingUseOfApacheHtaccessFiles) on Apache? Have you also set the correct RewriteBase in the `.htaccess` file?

If those are not the problem, I'm happy to help you via chat to get it working.

**Comment by crazywolf132** [comment]
Yeah, that is not the issuse... please add me on skype as i can show you via screenshare...

SKYPE: b2moon.au (from australia (crazywolf)))

**Comment by crazywolf132** [comment]
@lenton Please man, i really need your help.

**Comment by crazywolf132** [comment]
thankyou for your help.
